cask_args appdir: '/Applications'

tap 'thoughtbot/formulae'
brew 'rcm'

brew 'python2'
brew 'python3'
brew 'zsh'
brew 'git'
brew 'the_silver_searcher'
brew 'fzf'
brew 'mysql'
brew 'postgres'
brew 'redis'
brew 'ripgrep'

tap 'neovim/neovim'
brew 'neovim'

cask 'google-chrome'
cask 'postgres'
cask '1password'
cask 'alfred'
cask 'viscosity'
cask 'hipchat'
cask 'cleanmymac'
cask 'atom'
cask 'cyberduck'
cask 'spotify'
cask 'spotify-notifications'
