#!/bin/sh

source ~/.dotfiles/zshrc

ln -sv ~/.config/nvim ~/.vim
ln -sv ~/.config/nvim/init.vim ~/.vimrc

if hash git 2>/dev/null; then
	if [[ ! -d ~/.config/nvim/bundle/Vundle.vim ]]; then
		git clone https://github.com/VundleVim/Vundle.vim.git ~/.config/nvim/bundle/Vundle.vim
	fi

	$EDITOR -c "execute \"PluginInstall\" | qa"
fi

if [[ ! -d ~/.dasht ]]; then
	git clone https://github.com/sunaku/dasht ~/.dasht
else
	cd ~/.dasht && git pull origin master
fi

cp ~/.dotfiles/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist
