#!/bin/sh

if hash brew 2>/dev/null; then
	brew bundle install --file="$(dirname $RCRC)/Brewfile"

	if [ -d ~/.oh-my-zsh ]; then
		sh ~/.oh-my-zsh/tools/upgrade.sh
	else
                git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
                chsh -s /usr/local/bin/zsh
	fi
fi

