#!/usr/bin/env ruby

path = if File.symlink?(__FILE__)
         File.expand_path('../../lib/git_hook.rb', File.readlink(__FILE__))
       else
         File.expand_path('../../lib/git_hook.rb', __FILE__)
       end

if File.exist?(path)
  require path
  GitHook.post_commit
else
  puts 'GitHook not found'
end
